name: Bilalian
options:
  bundleIdPrefix: com.ibnseddik
packages:
  Adhan:
    url: https://github.com/batoulapps/adhan-swift
    branch: main
targets:
  Bilalian:
    type: application
    platform: tvOS
    deploymentTarget: "26.0"
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ibnseddik.bilalian
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Bilalian
        LSRequiresIPhoneOS: false
        UISupportedInterfaceOrientations~tvOS:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocationWhenInUseUsageDescription: "We use your location to calculate prayer times. It does not leave the device."
        NSLocationUsageDescription: "We use your location to calculate prayer times. It does not leave the device."
    dependencies:
      - package: Adhan
  BilalianTests:
    type: bundle.unit-test
    platform: tvOS
    sources:
      - Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Bilalian
